alias ..="cd .."
alias act="source venv/bin/activate || source .venv/bin/activate"
alias g="git"
alias grep="grep --color=auto"
alias la="ls --color=auto -la"
alias ll="ls --color=auto -l"
alias ls="ls --color=auto"
alias py="python3"
alias rr="source ~/.bashrc"
alias gnome-control-center="XDG_CURRENT_DESKTOP=GNOME /usr/bin/gnome-control-center"
alias sudo="sudo -E TMUX=$TMUX"  # avoid nvim killing sessions

if which sudo >/dev/null 2>&1; then
	alias apt="sudo apt"
	alias blkid="sudo blkid"
	alias cfdisk="sudo cfdisk"
	alias chroot="sudo chroot"
	alias dd="sudo dd status=progress conv=fdatasync"
	alias dmesg="sudo dmesg"
	alias dpkg="sudo dpkg"
	alias fdisk="sudo fdisk"
	alias losetup="sudo losetup"
	alias mount="sudo mount"
	alias ss="sudo su -"
	alias ufw="sudo ufw"
	alias umount="sudo umount"
	alias zyp="sudo zypper"
fi
