syntax on

let mapleader=' '

let g:netrw_liststyle=3
let g:netrw_bufsettings='noma nomod nu nobl nowrap ro'
autocmd filetype netrw nnoremap <buffer> <Space> :Ntree<CR>

set autoindent
set autoread
set background=dark
set backspace=indent,eol,start
set bdir=$HOME/.vim/bkp/
set clipboard=unnamedplus
set completeopt=menu,menuone,noselect
set dir=$HOME/.vim/swp/
set encoding=utf-8
set hidden
set hlsearch
set incsearch
set laststatus=2
set list listchars=tab:\~\ ,trail:~
set mouse=a
set number
set relativenumber
set ruler
set tabstop=4 softtabstop=4 shiftwidth=4 expandtab
set wildmenu

nnoremap - :Ex<CR>
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <leader><leader><leader><leader><leader><leader>l <Plug>NetrwRefresh
nnoremap <C-l> <C-w>l
nnoremap <C-w><C-t> :tabnew<CR>
nnoremap <Leader><Space> :nohlsearch<CR>
nnoremap <Leader>H :vertical resize +10<CR>
nnoremap <Leader>J :resize -10<CR>
nnoremap <Leader>K :resize +10<CR>
nnoremap <Leader>L :vertical resize -10<CR>
nnoremap <Leader>Q :qa<CR>
nnoremap <Leader>W :w !sudo tee % > /dev/null<CR>
nnoremap <Leader>rs :source ~/.vim/sessions/
nnoremap <Leader>ss :mksession! ~/.vim/sessions/
nnoremap <Leader>w :w<CR>
nnoremap <expr><silent> <Bar> v:count == 0 ? "<C-W>v<C-W><Right>" : ":<C-U>normal! 0".v:count."<Bar><CR>"
nnoremap <expr><silent> _ v:count == 0 ? "<C-W>s<C-W><Down>"  : ":<C-U>normal! ".v:count."_<CR>"
nnoremap <silent> <Leader>fws :let _s=@/<Bar>:%s/\s\+$//e<Bar>:let @/=_s<Bar>:nohl<CR>
nnoremap P :pu<CR>
nnoremap Y y$
vnoremap <Leader>p "_dP
vnoremap <Leader>y "+y

source $HOME/.vim/ccr.vim
source $HOME/.vim/tabline.vim
