vim.cmd.source(vim.fn.stdpath("config") .. "/ccr.vim")
require("config.autocmd")
require("config.options")
require("config.keymaps")
require("config.lazy")
require("utils.quickfix")
require("utils.tabmove")
