local opts = { noremap = true }

vim.g.mapleader = ' '

vim.api.nvim_set_keymap('n', '-', ':Ex<CR>', opts)
vim.api.nvim_set_keymap('n', '<Bar>', '<C-W>v<C-W><Right>', opts)
vim.api.nvim_set_keymap('n', '<C-h>', '<C-w>h', opts)
vim.api.nvim_set_keymap('n', '<C-j>', '<C-w>j', opts)
vim.api.nvim_set_keymap('n', '<C-k>', '<C-w>k', opts)
vim.api.nvim_set_keymap('n', '<C-l>', '<C-w>l', opts)
vim.api.nvim_set_keymap('n', '<C-w><C-t>', ':tabnew<CR>', opts)
vim.api.nvim_set_keymap('n', '<Leader><Leader><Leader><Leader><Leader><Leader>l', '<Plug>NetrwRefresh', opts)
vim.api.nvim_set_keymap('n', '<Leader><Space>', ':nohlsearch<CR>', opts)
vim.api.nvim_set_keymap('n', '<Leader>H', ':vertical resize +10<CR>', opts)
vim.api.nvim_set_keymap('n', '<Leader>J', ':resize -10<CR>', opts)
vim.api.nvim_set_keymap('n', '<Leader>K', ':resize +10<CR>', opts)
vim.api.nvim_set_keymap('n', '<Leader>L', ':vertical resize -10<CR>', opts)
vim.api.nvim_set_keymap('n', '<Leader>Q', ':qa<CR>', opts)
vim.api.nvim_set_keymap('n', '<Leader>W', ':w !sudo tee % > /dev/null<CR>', opts)
vim.api.nvim_set_keymap('n', '<Leader>rs', ':source ~/.config/nvim/sessions/', opts)
vim.api.nvim_set_keymap('n', '<Leader>ss', ':mksession! ~/.config/nvim/sessions/', opts)
vim.api.nvim_set_keymap('n', '<Leader>w', ':w<CR>', opts)
vim.api.nvim_set_keymap('n', 'P', ':pu<CR>', opts)
vim.api.nvim_set_keymap('n', 'Y', [[y$]], opts)
vim.api.nvim_set_keymap('n', '_', '<C-W>s<C-W><Down>', opts)
vim.api.nvim_set_keymap('v', '<Leader>p', [["_dP]], opts)
vim.api.nvim_set_keymap('v', '<Leader>y', [["+y]], opts)
